"""Generate a fully-unrolled, register-resident 64-point complex inverse DFT (unnormalized,
e^{+2 pi i k j / 64}) in CUDA C, radix-4 DIT, operating on float re[64], im[64].
Also emits a numpy self-test of the same schedule."""
import math, sys
N=64
def gen():
    lines=[]
    # radix-4 decimation-in-time on bit(quad)-reversed input order.
    # We generate stages explicitly: after digit-reversal load, 3 stages of 16 butterflies.
    # Digit reversal (base 4, 3 digits): index i -> rev(i)
    def rev4(i):
        d0,d1,d2=i%4,(i//4)%4,(i//16)%4
        return d0*16+d1*4+d2
    perm=[rev4(i) for i in range(N)]
    lines.append("// x_in[k] -> permuted working array (digit-reversed radix-4)")
    lines.append("#define FFT64_PERM(k) (" + ",".join(str(p) for p in perm) + ")")
    # stage loop: span s = 1,4,16 ; each butterfly group uses twiddles w^(j*N/(4s)) for j=0..s-1
    body=[]
    for stage,s in enumerate([1,4,16]):
        step=4*s
        body.append(f"    // ---- stage {stage} (span {s}) ----")
        for base in range(0,N,step):
            for j in range(s):
                i0,i1,i2,i3=base+j,base+j+s,base+j+2*s,base+j+3*s
                # twiddles: w1=e^{+2pi i j/(4s)}, w2=w1^2, w3=w1^3 (inverse sign +)
                def tw(m):
                    ang=2*math.pi*j*m/step
                    return math.cos(ang), math.sin(ang)
                terms=[]
                for m,idx in ((1,i1),(2,i2),(3,i3)):
                    c,sn=tw(m)
                    if j==0:
                        terms.append((f"re[{idx}]",f"im[{idx}]"))
                    else:
                        c=f"{c:.9e}f"; sn=f"{sn:.9e}f"
                        terms.append((f"({c}*re[{idx}] - {sn}*im[{idx}])",f"({sn}*re[{idx}] + {c}*im[{idx}])"))
                (a1r,a1i),(a2r,a2i),(a3r,a3i)=terms
                body.append("    {")
                body.append(f"      const float a0r=re[{i0}], a0i=im[{i0}];")
                body.append(f"      const float a1r={a1r}, a1i={a1i};")
                body.append(f"      const float a2r={a2r}, a2i={a2i};")
                body.append(f"      const float a3r={a3r}, a3i={a3i};")
                # radix-4 inverse butterfly: y0=a0+a1+a2+a3; y1=a0 + i a1 - a2 - i a3; y2=a0-a1+a2-a3; y3=a0 - i a1 - a2 + i a3
                body.append("      const float t0r=a0r+a2r, t0i=a0i+a2i, t1r=a0r-a2r, t1i=a0i-a2i;")
                body.append("      const float t2r=a1r+a3r, t2i=a1i+a3i, t3r=a1r-a3r, t3i=a1i-a3i;")
                body.append(f"      re[{i0}]=t0r+t2r; im[{i0}]=t0i+t2i;")
                body.append(f"      re[{i2}]=t0r-t2r; im[{i2}]=t0i-t2i;")
                # i*(t3) = (-t3i, t3r)
                body.append(f"      re[{i1}]=t1r-t3i; im[{i1}]=t1i+t3r;")
                body.append(f"      re[{i3}]=t1r+t3i; im[{i3}]=t1i-t3r;")
                body.append("    }")
    lines.append("__device__ __forceinline__ void ifft64_inplace(float* __restrict__ re, float* __restrict__ im) {")
    lines+=body
    lines.append("}")
    return "\n".join(lines), perm

code,perm=gen()
open(sys.argv[1] if len(sys.argv)>1 else "scratch/svd_search_opt/kernels/fft64_gen.cuh","w").write(
"// AUTO-GENERATED by gen_fft64.py -- unnormalized inverse 64-pt complex DFT, radix-4 DIT.\n"
"// Input must be loaded in digit-reversed order: work[i] = x[FFT64_PERM_i]; output natural order.\n#pragma once\n"+code+"\n")

# numpy self-test of the same schedule
import numpy as np
def run(x):
    re=[0.0]*N; im=[0.0]*N
    for i in range(N): re[i]=x[perm[i]].real; im[i]=x[perm[i]].imag
    for s in [1,4,16]:
        step=4*s
        for base in range(0,N,step):
            for j in range(s):
                i0,i1,i2,i3=base+j,base+j+s,base+j+2*s,base+j+3*s
                a=[complex(re[i0],im[i0])]
                for m,idx in ((1,i1),(2,i2),(3,i3)):
                    a.append(complex(re[idx],im[idx])*np.exp(2j*math.pi*j*m/step))
                a0,a1,a2,a3=a
                t0=a0+a2; t1=a0-a2; t2=a1+a3; t3=a1-a3
                y=[t0+t2, t1+1j*t3, t0-t2, t1-1j*t3]
                for idx,v in zip((i0,i1,i2,i3),y): re[idx]=v.real; im[idx]=v.imag
    return np.array([complex(r,i) for r,i in zip(re,im)])
x=np.random.randn(N)+1j*np.random.randn(N)
ref=np.fft.ifft(x)*N
print("gen_fft64 self-test max err:", np.abs(run(x)-ref).max(), " (perm ok:", sorted(perm)==list(range(N)),")")

# ---------------------------------------------------------------------------
# Lean-kernel preprocessing helpers (all twiddles as literal immediates).
# ---------------------------------------------------------------------------
def f(v): return f"{v:.9e}f"
out=[]
# (a) multiply X[k] by t256^k = e^{+2 pi i k/256}, k=1..63 (h=1 residue shift for n_psi=256)
out.append("__device__ __forceinline__ void twiddle_h1_256(float* __restrict__ re, float* __restrict__ im) {")
for k in range(1,64):
    c,s=math.cos(2*math.pi*k/256), math.sin(2*math.pi*k/256)
    out.append(f"  {{ const float r=re[{k}], i=im[{k}]; re[{k}]={f(c)}*r - {f(s)}*i; im[{k}]={f(s)}*r + {f(c)}*i; }}")
out.append("}")
# (b) Hermitian pack, in place:  Z[k] = H1[k] + i*H2[k],
#     H1[k] = (X[k] + conj(X[64-k]))/2,  H2[k] = (X[k] u_k + conj(X[64-k] u_{64-k}))/2,  u_k = e^{+2 pi i k/128}
out.append("__device__ __forceinline__ void hermitian_pack_inplace(float* __restrict__ re, float* __restrict__ im) {")
def uk(k): return math.cos(2*math.pi*k/128), math.sin(2*math.pi*k/128)
# k = 0 : H1 = Re X0 ; H2 = Re X0 (u_0 = 1)
out.append("  { const float r=re[0]; re[0]=r; im[0]=r; }")
# k = 32: H1 = Re X32 ; H2 = Re(i*X32) = -Im X32   (u_32 = i)
out.append("  { const float r=re[32], i=im[32]; re[32]=r; im[32]=-i; }")
for k in range(1,32):
    kp=64-k
    c1,s1=uk(k); c2,s2=uk(kp)
    out.append("  {")
    out.append(f"    const float ar=re[{k}], ai=im[{k}], br=re[{kp}], bi=im[{kp}];")
    out.append(f"    const float h1r=0.5f*(ar+br), h1i=0.5f*(ai-bi);")                     # H1[k] = (a + conj(b))/2
    out.append(f"    const float a2r={f(c1)}*ar - {f(s1)}*ai, a2i={f(s1)}*ar + {f(c1)}*ai;")  # a*u_k
    out.append(f"    const float b2r={f(c2)}*br - {f(s2)}*bi, b2i={f(s2)}*br + {f(c2)}*bi;")  # b*u_{64-k}
    out.append(f"    const float h2r=0.5f*(a2r+b2r), h2i=0.5f*(a2i-b2i);")                 # H2[k] = (a2 + conj(b2))/2
    out.append(f"    re[{k}]=h1r-h2i; im[{k}]=h1i+h2r;")        # Z[k]  = H1 + i H2
    out.append(f"    re[{kp}]=h1r+h2i; im[{kp}]=-h1i+h2r;")     # Z[64-k] = conj(H1) + i conj(H2)
    out.append("  }")
out.append("}")
with open(sys.argv[1] if len(sys.argv)>1 else "scratch/svd_search_opt/kernels/fft64_gen.cuh","a") as fh:
    fh.write("\n".join(out)+"\n")

# numpy end-to-end check of the lean math for n_psi=256 (R=4) and 128 (R=2)
def lean_corr(C, R):
    F=len(C); D=np.zeros(64,complex); D[:F]=C; D[1:]*=2
    T=R//2; NPSI=64*R; out=np.zeros(NPSI)
    t=np.exp(2j*np.pi*np.arange(64)/NPSI)
    for h in range(T):
        X=D*t**h
        # pack
        def herm(Xv): return 0.5*(Xv+np.conj(Xv[(-np.arange(64))%64]))
        u=np.exp(2j*np.pi*np.arange(64)/128)
        Z=herm(X)+1j*herm(X*u)
        G=np.fft.ifft(Z)*64
        out[R*np.arange(64)+h]=G.real; out[R*np.arange(64)+h+T]=G.imag
    return out
C=np.random.randn(64)+1j*np.random.randn(64); C[0]=C[0].real
for R in (2,4):
    ref=np.fft.irfft(np.concatenate([C,np.zeros(64*R//2+1-64)]), n=64*R)*64*R   # norm="forward"
    print(f"lean math R={R} (n_psi={64*R}) max err vs np.fft.irfft(norm=forward): {np.abs(lean_corr(C,R)-ref).max():.2e}")
