// AUTO-GENERATED by scratch/svd_search_opt/gen_fft64.py -- do not edit by hand. -- unnormalized inverse 64-pt complex DFT, radix-4 DIT.
// Input must be loaded in digit-reversed order: work[i] = x[FFT64_PERM_i]; output natural order.
#pragma once
// x_in[k] -> permuted working array (digit-reversed radix-4)
#define FFT64_PERM_LIST 0,16,32,48,4,20,36,52,8,24,40,56,12,28,44,60,1,17,33,49,5,21,37,53,9,25,41,57,13,29,45,61,2,18,34,50,6,22,38,54,10,26,42,58,14,30,46,62,3,19,35,51,7,23,39,55,11,27,43,59,15,31,47,63
__device__ __forceinline__ void ifft64_inplace(float* __restrict__ re, float* __restrict__ im) {
    // ---- stage 0 (span 1) ----
    {
      const float a0r=re[0], a0i=im[0];
      const float a1r=re[1], a1i=im[1];
      const float a2r=re[2], a2i=im[2];
      const float a3r=re[3], a3i=im[3];
      const float t0r=a0r+a2r, t0i=a0i+a2i, t1r=a0r-a2r, t1i=a0i-a2i;
      const float t2r=a1r+a3r, t2i=a1i+a3i, t3r=a1r-a3r, t3i=a1i-a3i;
      re[0]=t0r+t2r; im[0]=t0i+t2i;
      re[2]=t0r-t2r; im[2]=t0i-t2i;
      re[1]=t1r-t3i; im[1]=t1i+t3r;
      re[3]=t1r+t3i; im[3]=t1i-t3r;
    }
    {
      const float a0r=re[4], a0i=im[4];
      const float a1r=re[5], a1i=im[5];
      const float a2r=re[6], a2i=im[6];
      const float a3r=re[7], a3i=im[7];
      const float t0r=a0r+a2r, t0i=a0i+a2i, t1r=a0r-a2r, t1i=a0i-a2i;
      const float t2r=a1r+a3r, t2i=a1i+a3i, t3r=a1r-a3r, t3i=a1i-a3i;
      re[4]=t0r+t2r; im[4]=t0i+t2i;
      re[6]=t0r-t2r; im[6]=t0i-t2i;
      re[5]=t1r-t3i; im[5]=t1i+t3r;
      re[7]=t1r+t3i; im[7]=t1i-t3r;
    }
    {
      const float a0r=re[8], a0i=im[8];
      const float a1r=re[9], a1i=im[9];
      const float a2r=re[10], a2i=im[10];
      const float a3r=re[11], a3i=im[11];
      const float t0r=a0r+a2r, t0i=a0i+a2i, t1r=a0r-a2r, t1i=a0i-a2i;
      const float t2r=a1r+a3r, t2i=a1i+a3i, t3r=a1r-a3r, t3i=a1i-a3i;
      re[8]=t0r+t2r; im[8]=t0i+t2i;
      re[10]=t0r-t2r; im[10]=t0i-t2i;
      re[9]=t1r-t3i; im[9]=t1i+t3r;
      re[11]=t1r+t3i; im[11]=t1i-t3r;
    }
    {
      const float a0r=re[12], a0i=im[12];
      const float a1r=re[13], a1i=im[13];
      const float a2r=re[14], a2i=im[14];
      const float a3r=re[15], a3i=im[15];
      const float t0r=a0r+a2r, t0i=a0i+a2i, t1r=a0r-a2r, t1i=a0i-a2i;
      const float t2r=a1r+a3r, t2i=a1i+a3i, t3r=a1r-a3r, t3i=a1i-a3i;
      re[12]=t0r+t2r; im[12]=t0i+t2i;
      re[14]=t0r-t2r; im[14]=t0i-t2i;
      re[13]=t1r-t3i; im[13]=t1i+t3r;
      re[15]=t1r+t3i; im[15]=t1i-t3r;
    }
    {
      const float a0r=re[16], a0i=im[16];
      const float a1r=re[17], a1i=im[17];
      const float a2r=re[18], a2i=im[18];
      const float a3r=re[19], a3i=im[19];
      const float t0r=a0r+a2r, t0i=a0i+a2i, t1r=a0r-a2r, t1i=a0i-a2i;
      const float t2r=a1r+a3r, t2i=a1i+a3i, t3r=a1r-a3r, t3i=a1i-a3i;
      re[16]=t0r+t2r; im[16]=t0i+t2i;
      re[18]=t0r-t2r; im[18]=t0i-t2i;
      re[17]=t1r-t3i; im[17]=t1i+t3r;
      re[19]=t1r+t3i; im[19]=t1i-t3r;
    }
    {
      const float a0r=re[20], a0i=im[20];
      const float a1r=re[21], a1i=im[21];
      const float a2r=re[22], a2i=im[22];
      const float a3r=re[23], a3i=im[23];
      const float t0r=a0r+a2r, t0i=a0i+a2i, t1r=a0r-a2r, t1i=a0i-a2i;
      const float t2r=a1r+a3r, t2i=a1i+a3i, t3r=a1r-a3r, t3i=a1i-a3i;
      re[20]=t0r+t2r; im[20]=t0i+t2i;
      re[22]=t0r-t2r; im[22]=t0i-t2i;
      re[21]=t1r-t3i; im[21]=t1i+t3r;
      re[23]=t1r+t3i; im[23]=t1i-t3r;
    }
    {
      const float a0r=re[24], a0i=im[24];
      const float a1r=re[25], a1i=im[25];
      const float a2r=re[26], a2i=im[26];
      const float a3r=re[27], a3i=im[27];
      const float t0r=a0r+a2r, t0i=a0i+a2i, t1r=a0r-a2r, t1i=a0i-a2i;
      const float t2r=a1r+a3r, t2i=a1i+a3i, t3r=a1r-a3r, t3i=a1i-a3i;
      re[24]=t0r+t2r; im[24]=t0i+t2i;
      re[26]=t0r-t2r; im[26]=t0i-t2i;
      re[25]=t1r-t3i; im[25]=t1i+t3r;
      re[27]=t1r+t3i; im[27]=t1i-t3r;
    }
    {
      const float a0r=re[28], a0i=im[28];
      const float a1r=re[29], a1i=im[29];
      const float a2r=re[30], a2i=im[30];
      const float a3r=re[31], a3i=im[31];
      const float t0r=a0r+a2r, t0i=a0i+a2i, t1r=a0r-a2r, t1i=a0i-a2i;
      const float t2r=a1r+a3r, t2i=a1i+a3i, t3r=a1r-a3r, t3i=a1i-a3i;
      re[28]=t0r+t2r; im[28]=t0i+t2i;
      re[30]=t0r-t2r; im[30]=t0i-t2i;
      re[29]=t1r-t3i; im[29]=t1i+t3r;
      re[31]=t1r+t3i; im[31]=t1i-t3r;
    }
    {
      const float a0r=re[32], a0i=im[32];
      const float a1r=re[33], a1i=im[33];
      const float a2r=re[34], a2i=im[34];
      const float a3r=re[35], a3i=im[35];
      const float t0r=a0r+a2r, t0i=a0i+a2i, t1r=a0r-a2r, t1i=a0i-a2i;
      const float t2r=a1r+a3r, t2i=a1i+a3i, t3r=a1r-a3r, t3i=a1i-a3i;
      re[32]=t0r+t2r; im[32]=t0i+t2i;
      re[34]=t0r-t2r; im[34]=t0i-t2i;
      re[33]=t1r-t3i; im[33]=t1i+t3r;
      re[35]=t1r+t3i; im[35]=t1i-t3r;
    }
    {
      const float a0r=re[36], a0i=im[36];
      const float a1r=re[37], a1i=im[37];
      const float a2r=re[38], a2i=im[38];
      const float a3r=re[39], a3i=im[39];
      const float t0r=a0r+a2r, t0i=a0i+a2i, t1r=a0r-a2r, t1i=a0i-a2i;
      const float t2r=a1r+a3r, t2i=a1i+a3i, t3r=a1r-a3r, t3i=a1i-a3i;
      re[36]=t0r+t2r; im[36]=t0i+t2i;
      re[38]=t0r-t2r; im[38]=t0i-t2i;
      re[37]=t1r-t3i; im[37]=t1i+t3r;
      re[39]=t1r+t3i; im[39]=t1i-t3r;
    }
    {
      const float a0r=re[40], a0i=im[40];
      const float a1r=re[41], a1i=im[41];
      const float a2r=re[42], a2i=im[42];
      const float a3r=re[43], a3i=im[43];
      const float t0r=a0r+a2r, t0i=a0i+a2i, t1r=a0r-a2r, t1i=a0i-a2i;
      const float t2r=a1r+a3r, t2i=a1i+a3i, t3r=a1r-a3r, t3i=a1i-a3i;
      re[40]=t0r+t2r; im[40]=t0i+t2i;
      re[42]=t0r-t2r; im[42]=t0i-t2i;
      re[41]=t1r-t3i; im[41]=t1i+t3r;
      re[43]=t1r+t3i; im[43]=t1i-t3r;
    }
    {
      const float a0r=re[44], a0i=im[44];
      const float a1r=re[45], a1i=im[45];
      const float a2r=re[46], a2i=im[46];
      const float a3r=re[47], a3i=im[47];
      const float t0r=a0r+a2r, t0i=a0i+a2i, t1r=a0r-a2r, t1i=a0i-a2i;
      const float t2r=a1r+a3r, t2i=a1i+a3i, t3r=a1r-a3r, t3i=a1i-a3i;
      re[44]=t0r+t2r; im[44]=t0i+t2i;
      re[46]=t0r-t2r; im[46]=t0i-t2i;
      re[45]=t1r-t3i; im[45]=t1i+t3r;
      re[47]=t1r+t3i; im[47]=t1i-t3r;
    }
    {
      const float a0r=re[48], a0i=im[48];
      const float a1r=re[49], a1i=im[49];
      const float a2r=re[50], a2i=im[50];
      const float a3r=re[51], a3i=im[51];
      const float t0r=a0r+a2r, t0i=a0i+a2i, t1r=a0r-a2r, t1i=a0i-a2i;
      const float t2r=a1r+a3r, t2i=a1i+a3i, t3r=a1r-a3r, t3i=a1i-a3i;
      re[48]=t0r+t2r; im[48]=t0i+t2i;
      re[50]=t0r-t2r; im[50]=t0i-t2i;
      re[49]=t1r-t3i; im[49]=t1i+t3r;
      re[51]=t1r+t3i; im[51]=t1i-t3r;
    }
    {
      const float a0r=re[52], a0i=im[52];
      const float a1r=re[53], a1i=im[53];
      const float a2r=re[54], a2i=im[54];
      const float a3r=re[55], a3i=im[55];
      const float t0r=a0r+a2r, t0i=a0i+a2i, t1r=a0r-a2r, t1i=a0i-a2i;
      const float t2r=a1r+a3r, t2i=a1i+a3i, t3r=a1r-a3r, t3i=a1i-a3i;
      re[52]=t0r+t2r; im[52]=t0i+t2i;
      re[54]=t0r-t2r; im[54]=t0i-t2i;
      re[53]=t1r-t3i; im[53]=t1i+t3r;
      re[55]=t1r+t3i; im[55]=t1i-t3r;
    }
    {
      const float a0r=re[56], a0i=im[56];
      const float a1r=re[57], a1i=im[57];
      const float a2r=re[58], a2i=im[58];
      const float a3r=re[59], a3i=im[59];
      const float t0r=a0r+a2r, t0i=a0i+a2i, t1r=a0r-a2r, t1i=a0i-a2i;
      const float t2r=a1r+a3r, t2i=a1i+a3i, t3r=a1r-a3r, t3i=a1i-a3i;
      re[56]=t0r+t2r; im[56]=t0i+t2i;
      re[58]=t0r-t2r; im[58]=t0i-t2i;
      re[57]=t1r-t3i; im[57]=t1i+t3r;
      re[59]=t1r+t3i; im[59]=t1i-t3r;
    }
    {
      const float a0r=re[60], a0i=im[60];
      const float a1r=re[61], a1i=im[61];
      const float a2r=re[62], a2i=im[62];
      const float a3r=re[63], a3i=im[63];
      const float t0r=a0r+a2r, t0i=a0i+a2i, t1r=a0r-a2r, t1i=a0i-a2i;
      const float t2r=a1r+a3r, t2i=a1i+a3i, t3r=a1r-a3r, t3i=a1i-a3i;
      re[60]=t0r+t2r; im[60]=t0i+t2i;
      re[62]=t0r-t2r; im[62]=t0i-t2i;
      re[61]=t1r-t3i; im[61]=t1i+t3r;
      re[63]=t1r+t3i; im[63]=t1i-t3r;
    }
    // ---- stage 1 (span 4) ----
    {
      const float a0r=re[0], a0i=im[0];
      const float a1r=re[4], a1i=im[4];
      const float a2r=re[8], a2i=im[8];
      const float a3r=re[12], a3i=im[12];
      const float t0r=a0r+a2r, t0i=a0i+a2i, t1r=a0r-a2r, t1i=a0i-a2i;
      const float t2r=a1r+a3r, t2i=a1i+a3i, t3r=a1r-a3r, t3i=a1i-a3i;
      re[0]=t0r+t2r; im[0]=t0i+t2i;
      re[8]=t0r-t2r; im[8]=t0i-t2i;
      re[4]=t1r-t3i; im[4]=t1i+t3r;
      re[12]=t1r+t3i; im[12]=t1i-t3r;
    }
    {
      const float a0r=re[1], a0i=im[1];
      const float a1r=(9.238795325e-01f*re[5] - 3.826834324e-01f*im[5]), a1i=(3.826834324e-01f*re[5] + 9.238795325e-01f*im[5]);
      const float a2r=(7.071067812e-01f*re[9] - 7.071067812e-01f*im[9]), a2i=(7.071067812e-01f*re[9] + 7.071067812e-01f*im[9]);
      const float a3r=(3.826834324e-01f*re[13] - 9.238795325e-01f*im[13]), a3i=(9.238795325e-01f*re[13] + 3.826834324e-01f*im[13]);
      const float t0r=a0r+a2r, t0i=a0i+a2i, t1r=a0r-a2r, t1i=a0i-a2i;
      const float t2r=a1r+a3r, t2i=a1i+a3i, t3r=a1r-a3r, t3i=a1i-a3i;
      re[1]=t0r+t2r; im[1]=t0i+t2i;
      re[9]=t0r-t2r; im[9]=t0i-t2i;
      re[5]=t1r-t3i; im[5]=t1i+t3r;
      re[13]=t1r+t3i; im[13]=t1i-t3r;
    }
    {
      const float a0r=re[2], a0i=im[2];
      const float a1r=(7.071067812e-01f*re[6] - 7.071067812e-01f*im[6]), a1i=(7.071067812e-01f*re[6] + 7.071067812e-01f*im[6]);
      const float a2r=(6.123233996e-17f*re[10] - 1.000000000e+00f*im[10]), a2i=(1.000000000e+00f*re[10] + 6.123233996e-17f*im[10]);
      const float a3r=(-7.071067812e-01f*re[14] - 7.071067812e-01f*im[14]), a3i=(7.071067812e-01f*re[14] + -7.071067812e-01f*im[14]);
      const float t0r=a0r+a2r, t0i=a0i+a2i, t1r=a0r-a2r, t1i=a0i-a2i;
      const float t2r=a1r+a3r, t2i=a1i+a3i, t3r=a1r-a3r, t3i=a1i-a3i;
      re[2]=t0r+t2r; im[2]=t0i+t2i;
      re[10]=t0r-t2r; im[10]=t0i-t2i;
      re[6]=t1r-t3i; im[6]=t1i+t3r;
      re[14]=t1r+t3i; im[14]=t1i-t3r;
    }
    {
      const float a0r=re[3], a0i=im[3];
      const float a1r=(3.826834324e-01f*re[7] - 9.238795325e-01f*im[7]), a1i=(9.238795325e-01f*re[7] + 3.826834324e-01f*im[7]);
      const float a2r=(-7.071067812e-01f*re[11] - 7.071067812e-01f*im[11]), a2i=(7.071067812e-01f*re[11] + -7.071067812e-01f*im[11]);
      const float a3r=(-9.238795325e-01f*re[15] - -3.826834324e-01f*im[15]), a3i=(-3.826834324e-01f*re[15] + -9.238795325e-01f*im[15]);
      const float t0r=a0r+a2r, t0i=a0i+a2i, t1r=a0r-a2r, t1i=a0i-a2i;
      const float t2r=a1r+a3r, t2i=a1i+a3i, t3r=a1r-a3r, t3i=a1i-a3i;
      re[3]=t0r+t2r; im[3]=t0i+t2i;
      re[11]=t0r-t2r; im[11]=t0i-t2i;
      re[7]=t1r-t3i; im[7]=t1i+t3r;
      re[15]=t1r+t3i; im[15]=t1i-t3r;
    }
    {
      const float a0r=re[16], a0i=im[16];
      const float a1r=re[20], a1i=im[20];
      const float a2r=re[24], a2i=im[24];
      const float a3r=re[28], a3i=im[28];
      const float t0r=a0r+a2r, t0i=a0i+a2i, t1r=a0r-a2r, t1i=a0i-a2i;
      const float t2r=a1r+a3r, t2i=a1i+a3i, t3r=a1r-a3r, t3i=a1i-a3i;
      re[16]=t0r+t2r; im[16]=t0i+t2i;
      re[24]=t0r-t2r; im[24]=t0i-t2i;
      re[20]=t1r-t3i; im[20]=t1i+t3r;
      re[28]=t1r+t3i; im[28]=t1i-t3r;
    }
    {
      const float a0r=re[17], a0i=im[17];
      const float a1r=(9.238795325e-01f*re[21] - 3.826834324e-01f*im[21]), a1i=(3.826834324e-01f*re[21] + 9.238795325e-01f*im[21]);
      const float a2r=(7.071067812e-01f*re[25] - 7.071067812e-01f*im[25]), a2i=(7.071067812e-01f*re[25] + 7.071067812e-01f*im[25]);
      const float a3r=(3.826834324e-01f*re[29] - 9.238795325e-01f*im[29]), a3i=(9.238795325e-01f*re[29] + 3.826834324e-01f*im[29]);
      const float t0r=a0r+a2r, t0i=a0i+a2i, t1r=a0r-a2r, t1i=a0i-a2i;
      const float t2r=a1r+a3r, t2i=a1i+a3i, t3r=a1r-a3r, t3i=a1i-a3i;
      re[17]=t0r+t2r; im[17]=t0i+t2i;
      re[25]=t0r-t2r; im[25]=t0i-t2i;
      re[21]=t1r-t3i; im[21]=t1i+t3r;
      re[29]=t1r+t3i; im[29]=t1i-t3r;
    }
    {
      const float a0r=re[18], a0i=im[18];
      const float a1r=(7.071067812e-01f*re[22] - 7.071067812e-01f*im[22]), a1i=(7.071067812e-01f*re[22] + 7.071067812e-01f*im[22]);
      const float a2r=(6.123233996e-17f*re[26] - 1.000000000e+00f*im[26]), a2i=(1.000000000e+00f*re[26] + 6.123233996e-17f*im[26]);
      const float a3r=(-7.071067812e-01f*re[30] - 7.071067812e-01f*im[30]), a3i=(7.071067812e-01f*re[30] + -7.071067812e-01f*im[30]);
      const float t0r=a0r+a2r, t0i=a0i+a2i, t1r=a0r-a2r, t1i=a0i-a2i;
      const float t2r=a1r+a3r, t2i=a1i+a3i, t3r=a1r-a3r, t3i=a1i-a3i;
      re[18]=t0r+t2r; im[18]=t0i+t2i;
      re[26]=t0r-t2r; im[26]=t0i-t2i;
      re[22]=t1r-t3i; im[22]=t1i+t3r;
      re[30]=t1r+t3i; im[30]=t1i-t3r;
    }
    {
      const float a0r=re[19], a0i=im[19];
      const float a1r=(3.826834324e-01f*re[23] - 9.238795325e-01f*im[23]), a1i=(9.238795325e-01f*re[23] + 3.826834324e-01f*im[23]);
      const float a2r=(-7.071067812e-01f*re[27] - 7.071067812e-01f*im[27]), a2i=(7.071067812e-01f*re[27] + -7.071067812e-01f*im[27]);
      const float a3r=(-9.238795325e-01f*re[31] - -3.826834324e-01f*im[31]), a3i=(-3.826834324e-01f*re[31] + -9.238795325e-01f*im[31]);
      const float t0r=a0r+a2r, t0i=a0i+a2i, t1r=a0r-a2r, t1i=a0i-a2i;
      const float t2r=a1r+a3r, t2i=a1i+a3i, t3r=a1r-a3r, t3i=a1i-a3i;
      re[19]=t0r+t2r; im[19]=t0i+t2i;
      re[27]=t0r-t2r; im[27]=t0i-t2i;
      re[23]=t1r-t3i; im[23]=t1i+t3r;
      re[31]=t1r+t3i; im[31]=t1i-t3r;
    }
    {
      const float a0r=re[32], a0i=im[32];
      const float a1r=re[36], a1i=im[36];
      const float a2r=re[40], a2i=im[40];
      const float a3r=re[44], a3i=im[44];
      const float t0r=a0r+a2r, t0i=a0i+a2i, t1r=a0r-a2r, t1i=a0i-a2i;
      const float t2r=a1r+a3r, t2i=a1i+a3i, t3r=a1r-a3r, t3i=a1i-a3i;
      re[32]=t0r+t2r; im[32]=t0i+t2i;
      re[40]=t0r-t2r; im[40]=t0i-t2i;
      re[36]=t1r-t3i; im[36]=t1i+t3r;
      re[44]=t1r+t3i; im[44]=t1i-t3r;
    }
    {
      const float a0r=re[33], a0i=im[33];
      const float a1r=(9.238795325e-01f*re[37] - 3.826834324e-01f*im[37]), a1i=(3.826834324e-01f*re[37] + 9.238795325e-01f*im[37]);
      const float a2r=(7.071067812e-01f*re[41] - 7.071067812e-01f*im[41]), a2i=(7.071067812e-01f*re[41] + 7.071067812e-01f*im[41]);
      const float a3r=(3.826834324e-01f*re[45] - 9.238795325e-01f*im[45]), a3i=(9.238795325e-01f*re[45] + 3.826834324e-01f*im[45]);
      const float t0r=a0r+a2r, t0i=a0i+a2i, t1r=a0r-a2r, t1i=a0i-a2i;
      const float t2r=a1r+a3r, t2i=a1i+a3i, t3r=a1r-a3r, t3i=a1i-a3i;
      re[33]=t0r+t2r; im[33]=t0i+t2i;
      re[41]=t0r-t2r; im[41]=t0i-t2i;
      re[37]=t1r-t3i; im[37]=t1i+t3r;
      re[45]=t1r+t3i; im[45]=t1i-t3r;
    }
    {
      const float a0r=re[34], a0i=im[34];
      const float a1r=(7.071067812e-01f*re[38] - 7.071067812e-01f*im[38]), a1i=(7.071067812e-01f*re[38] + 7.071067812e-01f*im[38]);
      const float a2r=(6.123233996e-17f*re[42] - 1.000000000e+00f*im[42]), a2i=(1.000000000e+00f*re[42] + 6.123233996e-17f*im[42]);
      const float a3r=(-7.071067812e-01f*re[46] - 7.071067812e-01f*im[46]), a3i=(7.071067812e-01f*re[46] + -7.071067812e-01f*im[46]);
      const float t0r=a0r+a2r, t0i=a0i+a2i, t1r=a0r-a2r, t1i=a0i-a2i;
      const float t2r=a1r+a3r, t2i=a1i+a3i, t3r=a1r-a3r, t3i=a1i-a3i;
      re[34]=t0r+t2r; im[34]=t0i+t2i;
      re[42]=t0r-t2r; im[42]=t0i-t2i;
      re[38]=t1r-t3i; im[38]=t1i+t3r;
      re[46]=t1r+t3i; im[46]=t1i-t3r;
    }
    {
      const float a0r=re[35], a0i=im[35];
      const float a1r=(3.826834324e-01f*re[39] - 9.238795325e-01f*im[39]), a1i=(9.238795325e-01f*re[39] + 3.826834324e-01f*im[39]);
      const float a2r=(-7.071067812e-01f*re[43] - 7.071067812e-01f*im[43]), a2i=(7.071067812e-01f*re[43] + -7.071067812e-01f*im[43]);
      const float a3r=(-9.238795325e-01f*re[47] - -3.826834324e-01f*im[47]), a3i=(-3.826834324e-01f*re[47] + -9.238795325e-01f*im[47]);
      const float t0r=a0r+a2r, t0i=a0i+a2i, t1r=a0r-a2r, t1i=a0i-a2i;
      const float t2r=a1r+a3r, t2i=a1i+a3i, t3r=a1r-a3r, t3i=a1i-a3i;
      re[35]=t0r+t2r; im[35]=t0i+t2i;
      re[43]=t0r-t2r; im[43]=t0i-t2i;
      re[39]=t1r-t3i; im[39]=t1i+t3r;
      re[47]=t1r+t3i; im[47]=t1i-t3r;
    }
    {
      const float a0r=re[48], a0i=im[48];
      const float a1r=re[52], a1i=im[52];
      const float a2r=re[56], a2i=im[56];
      const float a3r=re[60], a3i=im[60];
      const float t0r=a0r+a2r, t0i=a0i+a2i, t1r=a0r-a2r, t1i=a0i-a2i;
      const float t2r=a1r+a3r, t2i=a1i+a3i, t3r=a1r-a3r, t3i=a1i-a3i;
      re[48]=t0r+t2r; im[48]=t0i+t2i;
      re[56]=t0r-t2r; im[56]=t0i-t2i;
      re[52]=t1r-t3i; im[52]=t1i+t3r;
      re[60]=t1r+t3i; im[60]=t1i-t3r;
    }
    {
      const float a0r=re[49], a0i=im[49];
      const float a1r=(9.238795325e-01f*re[53] - 3.826834324e-01f*im[53]), a1i=(3.826834324e-01f*re[53] + 9.238795325e-01f*im[53]);
      const float a2r=(7.071067812e-01f*re[57] - 7.071067812e-01f*im[57]), a2i=(7.071067812e-01f*re[57] + 7.071067812e-01f*im[57]);
      const float a3r=(3.826834324e-01f*re[61] - 9.238795325e-01f*im[61]), a3i=(9.238795325e-01f*re[61] + 3.826834324e-01f*im[61]);
      const float t0r=a0r+a2r, t0i=a0i+a2i, t1r=a0r-a2r, t1i=a0i-a2i;
      const float t2r=a1r+a3r, t2i=a1i+a3i, t3r=a1r-a3r, t3i=a1i-a3i;
      re[49]=t0r+t2r; im[49]=t0i+t2i;
      re[57]=t0r-t2r; im[57]=t0i-t2i;
      re[53]=t1r-t3i; im[53]=t1i+t3r;
      re[61]=t1r+t3i; im[61]=t1i-t3r;
    }
    {
      const float a0r=re[50], a0i=im[50];
      const float a1r=(7.071067812e-01f*re[54] - 7.071067812e-01f*im[54]), a1i=(7.071067812e-01f*re[54] + 7.071067812e-01f*im[54]);
      const float a2r=(6.123233996e-17f*re[58] - 1.000000000e+00f*im[58]), a2i=(1.000000000e+00f*re[58] + 6.123233996e-17f*im[58]);
      const float a3r=(-7.071067812e-01f*re[62] - 7.071067812e-01f*im[62]), a3i=(7.071067812e-01f*re[62] + -7.071067812e-01f*im[62]);
      const float t0r=a0r+a2r, t0i=a0i+a2i, t1r=a0r-a2r, t1i=a0i-a2i;
      const float t2r=a1r+a3r, t2i=a1i+a3i, t3r=a1r-a3r, t3i=a1i-a3i;
      re[50]=t0r+t2r; im[50]=t0i+t2i;
      re[58]=t0r-t2r; im[58]=t0i-t2i;
      re[54]=t1r-t3i; im[54]=t1i+t3r;
      re[62]=t1r+t3i; im[62]=t1i-t3r;
    }
    {
      const float a0r=re[51], a0i=im[51];
      const float a1r=(3.826834324e-01f*re[55] - 9.238795325e-01f*im[55]), a1i=(9.238795325e-01f*re[55] + 3.826834324e-01f*im[55]);
      const float a2r=(-7.071067812e-01f*re[59] - 7.071067812e-01f*im[59]), a2i=(7.071067812e-01f*re[59] + -7.071067812e-01f*im[59]);
      const float a3r=(-9.238795325e-01f*re[63] - -3.826834324e-01f*im[63]), a3i=(-3.826834324e-01f*re[63] + -9.238795325e-01f*im[63]);
      const float t0r=a0r+a2r, t0i=a0i+a2i, t1r=a0r-a2r, t1i=a0i-a2i;
      const float t2r=a1r+a3r, t2i=a1i+a3i, t3r=a1r-a3r, t3i=a1i-a3i;
      re[51]=t0r+t2r; im[51]=t0i+t2i;
      re[59]=t0r-t2r; im[59]=t0i-t2i;
      re[55]=t1r-t3i; im[55]=t1i+t3r;
      re[63]=t1r+t3i; im[63]=t1i-t3r;
    }
    // ---- stage 2 (span 16) ----
    {
      const float a0r=re[0], a0i=im[0];
      const float a1r=re[16], a1i=im[16];
      const float a2r=re[32], a2i=im[32];
      const float a3r=re[48], a3i=im[48];
      const float t0r=a0r+a2r, t0i=a0i+a2i, t1r=a0r-a2r, t1i=a0i-a2i;
      const float t2r=a1r+a3r, t2i=a1i+a3i, t3r=a1r-a3r, t3i=a1i-a3i;
      re[0]=t0r+t2r; im[0]=t0i+t2i;
      re[32]=t0r-t2r; im[32]=t0i-t2i;
      re[16]=t1r-t3i; im[16]=t1i+t3r;
      re[48]=t1r+t3i; im[48]=t1i-t3r;
    }
    {
      const float a0r=re[1], a0i=im[1];
      const float a1r=(9.951847267e-01f*re[17] - 9.801714033e-02f*im[17]), a1i=(9.801714033e-02f*re[17] + 9.951847267e-01f*im[17]);
      const float a2r=(9.807852804e-01f*re[33] - 1.950903220e-01f*im[33]), a2i=(1.950903220e-01f*re[33] + 9.807852804e-01f*im[33]);
      const float a3r=(9.569403357e-01f*re[49] - 2.902846773e-01f*im[49]), a3i=(2.902846773e-01f*re[49] + 9.569403357e-01f*im[49]);
      const float t0r=a0r+a2r, t0i=a0i+a2i, t1r=a0r-a2r, t1i=a0i-a2i;
      const float t2r=a1r+a3r, t2i=a1i+a3i, t3r=a1r-a3r, t3i=a1i-a3i;
      re[1]=t0r+t2r; im[1]=t0i+t2i;
      re[33]=t0r-t2r; im[33]=t0i-t2i;
      re[17]=t1r-t3i; im[17]=t1i+t3r;
      re[49]=t1r+t3i; im[49]=t1i-t3r;
    }
    {
      const float a0r=re[2], a0i=im[2];
      const float a1r=(9.807852804e-01f*re[18] - 1.950903220e-01f*im[18]), a1i=(1.950903220e-01f*re[18] + 9.807852804e-01f*im[18]);
      const float a2r=(9.238795325e-01f*re[34] - 3.826834324e-01f*im[34]), a2i=(3.826834324e-01f*re[34] + 9.238795325e-01f*im[34]);
      const float a3r=(8.314696123e-01f*re[50] - 5.555702330e-01f*im[50]), a3i=(5.555702330e-01f*re[50] + 8.314696123e-01f*im[50]);
      const float t0r=a0r+a2r, t0i=a0i+a2i, t1r=a0r-a2r, t1i=a0i-a2i;
      const float t2r=a1r+a3r, t2i=a1i+a3i, t3r=a1r-a3r, t3i=a1i-a3i;
      re[2]=t0r+t2r; im[2]=t0i+t2i;
      re[34]=t0r-t2r; im[34]=t0i-t2i;
      re[18]=t1r-t3i; im[18]=t1i+t3r;
      re[50]=t1r+t3i; im[50]=t1i-t3r;
    }
    {
      const float a0r=re[3], a0i=im[3];
      const float a1r=(9.569403357e-01f*re[19] - 2.902846773e-01f*im[19]), a1i=(2.902846773e-01f*re[19] + 9.569403357e-01f*im[19]);
      const float a2r=(8.314696123e-01f*re[35] - 5.555702330e-01f*im[35]), a2i=(5.555702330e-01f*re[35] + 8.314696123e-01f*im[35]);
      const float a3r=(6.343932842e-01f*re[51] - 7.730104534e-01f*im[51]), a3i=(7.730104534e-01f*re[51] + 6.343932842e-01f*im[51]);
      const float t0r=a0r+a2r, t0i=a0i+a2i, t1r=a0r-a2r, t1i=a0i-a2i;
      const float t2r=a1r+a3r, t2i=a1i+a3i, t3r=a1r-a3r, t3i=a1i-a3i;
      re[3]=t0r+t2r; im[3]=t0i+t2i;
      re[35]=t0r-t2r; im[35]=t0i-t2i;
      re[19]=t1r-t3i; im[19]=t1i+t3r;
      re[51]=t1r+t3i; im[51]=t1i-t3r;
    }
    {
      const float a0r=re[4], a0i=im[4];
      const float a1r=(9.238795325e-01f*re[20] - 3.826834324e-01f*im[20]), a1i=(3.826834324e-01f*re[20] + 9.238795325e-01f*im[20]);
      const float a2r=(7.071067812e-01f*re[36] - 7.071067812e-01f*im[36]), a2i=(7.071067812e-01f*re[36] + 7.071067812e-01f*im[36]);
      const float a3r=(3.826834324e-01f*re[52] - 9.238795325e-01f*im[52]), a3i=(9.238795325e-01f*re[52] + 3.826834324e-01f*im[52]);
      const float t0r=a0r+a2r, t0i=a0i+a2i, t1r=a0r-a2r, t1i=a0i-a2i;
      const float t2r=a1r+a3r, t2i=a1i+a3i, t3r=a1r-a3r, t3i=a1i-a3i;
      re[4]=t0r+t2r; im[4]=t0i+t2i;
      re[36]=t0r-t2r; im[36]=t0i-t2i;
      re[20]=t1r-t3i; im[20]=t1i+t3r;
      re[52]=t1r+t3i; im[52]=t1i-t3r;
    }
    {
      const float a0r=re[5], a0i=im[5];
      const float a1r=(8.819212643e-01f*re[21] - 4.713967368e-01f*im[21]), a1i=(4.713967368e-01f*re[21] + 8.819212643e-01f*im[21]);
      const float a2r=(5.555702330e-01f*re[37] - 8.314696123e-01f*im[37]), a2i=(8.314696123e-01f*re[37] + 5.555702330e-01f*im[37]);
      const float a3r=(9.801714033e-02f*re[53] - 9.951847267e-01f*im[53]), a3i=(9.951847267e-01f*re[53] + 9.801714033e-02f*im[53]);
      const float t0r=a0r+a2r, t0i=a0i+a2i, t1r=a0r-a2r, t1i=a0i-a2i;
      const float t2r=a1r+a3r, t2i=a1i+a3i, t3r=a1r-a3r, t3i=a1i-a3i;
      re[5]=t0r+t2r; im[5]=t0i+t2i;
      re[37]=t0r-t2r; im[37]=t0i-t2i;
      re[21]=t1r-t3i; im[21]=t1i+t3r;
      re[53]=t1r+t3i; im[53]=t1i-t3r;
    }
    {
      const float a0r=re[6], a0i=im[6];
      const float a1r=(8.314696123e-01f*re[22] - 5.555702330e-01f*im[22]), a1i=(5.555702330e-01f*re[22] + 8.314696123e-01f*im[22]);
      const float a2r=(3.826834324e-01f*re[38] - 9.238795325e-01f*im[38]), a2i=(9.238795325e-01f*re[38] + 3.826834324e-01f*im[38]);
      const float a3r=(-1.950903220e-01f*re[54] - 9.807852804e-01f*im[54]), a3i=(9.807852804e-01f*re[54] + -1.950903220e-01f*im[54]);
      const float t0r=a0r+a2r, t0i=a0i+a2i, t1r=a0r-a2r, t1i=a0i-a2i;
      const float t2r=a1r+a3r, t2i=a1i+a3i, t3r=a1r-a3r, t3i=a1i-a3i;
      re[6]=t0r+t2r; im[6]=t0i+t2i;
      re[38]=t0r-t2r; im[38]=t0i-t2i;
      re[22]=t1r-t3i; im[22]=t1i+t3r;
      re[54]=t1r+t3i; im[54]=t1i-t3r;
    }
    {
      const float a0r=re[7], a0i=im[7];
      const float a1r=(7.730104534e-01f*re[23] - 6.343932842e-01f*im[23]), a1i=(6.343932842e-01f*re[23] + 7.730104534e-01f*im[23]);
      const float a2r=(1.950903220e-01f*re[39] - 9.807852804e-01f*im[39]), a2i=(9.807852804e-01f*re[39] + 1.950903220e-01f*im[39]);
      const float a3r=(-4.713967368e-01f*re[55] - 8.819212643e-01f*im[55]), a3i=(8.819212643e-01f*re[55] + -4.713967368e-01f*im[55]);
      const float t0r=a0r+a2r, t0i=a0i+a2i, t1r=a0r-a2r, t1i=a0i-a2i;
      const float t2r=a1r+a3r, t2i=a1i+a3i, t3r=a1r-a3r, t3i=a1i-a3i;
      re[7]=t0r+t2r; im[7]=t0i+t2i;
      re[39]=t0r-t2r; im[39]=t0i-t2i;
      re[23]=t1r-t3i; im[23]=t1i+t3r;
      re[55]=t1r+t3i; im[55]=t1i-t3r;
    }
    {
      const float a0r=re[8], a0i=im[8];
      const float a1r=(7.071067812e-01f*re[24] - 7.071067812e-01f*im[24]), a1i=(7.071067812e-01f*re[24] + 7.071067812e-01f*im[24]);
      const float a2r=(6.123233996e-17f*re[40] - 1.000000000e+00f*im[40]), a2i=(1.000000000e+00f*re[40] + 6.123233996e-17f*im[40]);
      const float a3r=(-7.071067812e-01f*re[56] - 7.071067812e-01f*im[56]), a3i=(7.071067812e-01f*re[56] + -7.071067812e-01f*im[56]);
      const float t0r=a0r+a2r, t0i=a0i+a2i, t1r=a0r-a2r, t1i=a0i-a2i;
      const float t2r=a1r+a3r, t2i=a1i+a3i, t3r=a1r-a3r, t3i=a1i-a3i;
      re[8]=t0r+t2r; im[8]=t0i+t2i;
      re[40]=t0r-t2r; im[40]=t0i-t2i;
      re[24]=t1r-t3i; im[24]=t1i+t3r;
      re[56]=t1r+t3i; im[56]=t1i-t3r;
    }
    {
      const float a0r=re[9], a0i=im[9];
      const float a1r=(6.343932842e-01f*re[25] - 7.730104534e-01f*im[25]), a1i=(7.730104534e-01f*re[25] + 6.343932842e-01f*im[25]);
      const float a2r=(-1.950903220e-01f*re[41] - 9.807852804e-01f*im[41]), a2i=(9.807852804e-01f*re[41] + -1.950903220e-01f*im[41]);
      const float a3r=(-8.819212643e-01f*re[57] - 4.713967368e-01f*im[57]), a3i=(4.713967368e-01f*re[57] + -8.819212643e-01f*im[57]);
      const float t0r=a0r+a2r, t0i=a0i+a2i, t1r=a0r-a2r, t1i=a0i-a2i;
      const float t2r=a1r+a3r, t2i=a1i+a3i, t3r=a1r-a3r, t3i=a1i-a3i;
      re[9]=t0r+t2r; im[9]=t0i+t2i;
      re[41]=t0r-t2r; im[41]=t0i-t2i;
      re[25]=t1r-t3i; im[25]=t1i+t3r;
      re[57]=t1r+t3i; im[57]=t1i-t3r;
    }
    {
      const float a0r=re[10], a0i=im[10];
      const float a1r=(5.555702330e-01f*re[26] - 8.314696123e-01f*im[26]), a1i=(8.314696123e-01f*re[26] + 5.555702330e-01f*im[26]);
      const float a2r=(-3.826834324e-01f*re[42] - 9.238795325e-01f*im[42]), a2i=(9.238795325e-01f*re[42] + -3.826834324e-01f*im[42]);
      const float a3r=(-9.807852804e-01f*re[58] - 1.950903220e-01f*im[58]), a3i=(1.950903220e-01f*re[58] + -9.807852804e-01f*im[58]);
      const float t0r=a0r+a2r, t0i=a0i+a2i, t1r=a0r-a2r, t1i=a0i-a2i;
      const float t2r=a1r+a3r, t2i=a1i+a3i, t3r=a1r-a3r, t3i=a1i-a3i;
      re[10]=t0r+t2r; im[10]=t0i+t2i;
      re[42]=t0r-t2r; im[42]=t0i-t2i;
      re[26]=t1r-t3i; im[26]=t1i+t3r;
      re[58]=t1r+t3i; im[58]=t1i-t3r;
    }
    {
      const float a0r=re[11], a0i=im[11];
      const float a1r=(4.713967368e-01f*re[27] - 8.819212643e-01f*im[27]), a1i=(8.819212643e-01f*re[27] + 4.713967368e-01f*im[27]);
      const float a2r=(-5.555702330e-01f*re[43] - 8.314696123e-01f*im[43]), a2i=(8.314696123e-01f*re[43] + -5.555702330e-01f*im[43]);
      const float a3r=(-9.951847267e-01f*re[59] - -9.801714033e-02f*im[59]), a3i=(-9.801714033e-02f*re[59] + -9.951847267e-01f*im[59]);
      const float t0r=a0r+a2r, t0i=a0i+a2i, t1r=a0r-a2r, t1i=a0i-a2i;
      const float t2r=a1r+a3r, t2i=a1i+a3i, t3r=a1r-a3r, t3i=a1i-a3i;
      re[11]=t0r+t2r; im[11]=t0i+t2i;
      re[43]=t0r-t2r; im[43]=t0i-t2i;
      re[27]=t1r-t3i; im[27]=t1i+t3r;
      re[59]=t1r+t3i; im[59]=t1i-t3r;
    }
    {
      const float a0r=re[12], a0i=im[12];
      const float a1r=(3.826834324e-01f*re[28] - 9.238795325e-01f*im[28]), a1i=(9.238795325e-01f*re[28] + 3.826834324e-01f*im[28]);
      const float a2r=(-7.071067812e-01f*re[44] - 7.071067812e-01f*im[44]), a2i=(7.071067812e-01f*re[44] + -7.071067812e-01f*im[44]);
      const float a3r=(-9.238795325e-01f*re[60] - -3.826834324e-01f*im[60]), a3i=(-3.826834324e-01f*re[60] + -9.238795325e-01f*im[60]);
      const float t0r=a0r+a2r, t0i=a0i+a2i, t1r=a0r-a2r, t1i=a0i-a2i;
      const float t2r=a1r+a3r, t2i=a1i+a3i, t3r=a1r-a3r, t3i=a1i-a3i;
      re[12]=t0r+t2r; im[12]=t0i+t2i;
      re[44]=t0r-t2r; im[44]=t0i-t2i;
      re[28]=t1r-t3i; im[28]=t1i+t3r;
      re[60]=t1r+t3i; im[60]=t1i-t3r;
    }
    {
      const float a0r=re[13], a0i=im[13];
      const float a1r=(2.902846773e-01f*re[29] - 9.569403357e-01f*im[29]), a1i=(9.569403357e-01f*re[29] + 2.902846773e-01f*im[29]);
      const float a2r=(-8.314696123e-01f*re[45] - 5.555702330e-01f*im[45]), a2i=(5.555702330e-01f*re[45] + -8.314696123e-01f*im[45]);
      const float a3r=(-7.730104534e-01f*re[61] - -6.343932842e-01f*im[61]), a3i=(-6.343932842e-01f*re[61] + -7.730104534e-01f*im[61]);
      const float t0r=a0r+a2r, t0i=a0i+a2i, t1r=a0r-a2r, t1i=a0i-a2i;
      const float t2r=a1r+a3r, t2i=a1i+a3i, t3r=a1r-a3r, t3i=a1i-a3i;
      re[13]=t0r+t2r; im[13]=t0i+t2i;
      re[45]=t0r-t2r; im[45]=t0i-t2i;
      re[29]=t1r-t3i; im[29]=t1i+t3r;
      re[61]=t1r+t3i; im[61]=t1i-t3r;
    }
    {
      const float a0r=re[14], a0i=im[14];
      const float a1r=(1.950903220e-01f*re[30] - 9.807852804e-01f*im[30]), a1i=(9.807852804e-01f*re[30] + 1.950903220e-01f*im[30]);
      const float a2r=(-9.238795325e-01f*re[46] - 3.826834324e-01f*im[46]), a2i=(3.826834324e-01f*re[46] + -9.238795325e-01f*im[46]);
      const float a3r=(-5.555702330e-01f*re[62] - -8.314696123e-01f*im[62]), a3i=(-8.314696123e-01f*re[62] + -5.555702330e-01f*im[62]);
      const float t0r=a0r+a2r, t0i=a0i+a2i, t1r=a0r-a2r, t1i=a0i-a2i;
      const float t2r=a1r+a3r, t2i=a1i+a3i, t3r=a1r-a3r, t3i=a1i-a3i;
      re[14]=t0r+t2r; im[14]=t0i+t2i;
      re[46]=t0r-t2r; im[46]=t0i-t2i;
      re[30]=t1r-t3i; im[30]=t1i+t3r;
      re[62]=t1r+t3i; im[62]=t1i-t3r;
    }
    {
      const float a0r=re[15], a0i=im[15];
      const float a1r=(9.801714033e-02f*re[31] - 9.951847267e-01f*im[31]), a1i=(9.951847267e-01f*re[31] + 9.801714033e-02f*im[31]);
      const float a2r=(-9.807852804e-01f*re[47] - 1.950903220e-01f*im[47]), a2i=(1.950903220e-01f*re[47] + -9.807852804e-01f*im[47]);
      const float a3r=(-2.902846773e-01f*re[63] - -9.569403357e-01f*im[63]), a3i=(-9.569403357e-01f*re[63] + -2.902846773e-01f*im[63]);
      const float t0r=a0r+a2r, t0i=a0i+a2i, t1r=a0r-a2r, t1i=a0i-a2i;
      const float t2r=a1r+a3r, t2i=a1i+a3i, t3r=a1r-a3r, t3i=a1i-a3i;
      re[15]=t0r+t2r; im[15]=t0i+t2i;
      re[47]=t0r-t2r; im[47]=t0i-t2i;
      re[31]=t1r-t3i; im[31]=t1i+t3r;
      re[63]=t1r+t3i; im[63]=t1i-t3r;
    }
}
__device__ __forceinline__ void twiddle_h1_256(float* __restrict__ re, float* __restrict__ im) {
  { const float r=re[1], i=im[1]; re[1]=9.996988187e-01f*r - 2.454122852e-02f*i; im[1]=2.454122852e-02f*r + 9.996988187e-01f*i; }
  { const float r=re[2], i=im[2]; re[2]=9.987954562e-01f*r - 4.906767433e-02f*i; im[2]=4.906767433e-02f*r + 9.987954562e-01f*i; }
  { const float r=re[3], i=im[3]; re[3]=9.972904567e-01f*r - 7.356456360e-02f*i; im[3]=7.356456360e-02f*r + 9.972904567e-01f*i; }
  { const float r=re[4], i=im[4]; re[4]=9.951847267e-01f*r - 9.801714033e-02f*i; im[4]=9.801714033e-02f*r + 9.951847267e-01f*i; }
  { const float r=re[5], i=im[5]; re[5]=9.924795346e-01f*r - 1.224106752e-01f*i; im[5]=1.224106752e-01f*r + 9.924795346e-01f*i; }
  { const float r=re[6], i=im[6]; re[6]=9.891765100e-01f*r - 1.467304745e-01f*i; im[6]=1.467304745e-01f*r + 9.891765100e-01f*i; }
  { const float r=re[7], i=im[7]; re[7]=9.852776424e-01f*r - 1.709618888e-01f*i; im[7]=1.709618888e-01f*r + 9.852776424e-01f*i; }
  { const float r=re[8], i=im[8]; re[8]=9.807852804e-01f*r - 1.950903220e-01f*i; im[8]=1.950903220e-01f*r + 9.807852804e-01f*i; }
  { const float r=re[9], i=im[9]; re[9]=9.757021300e-01f*r - 2.191012402e-01f*i; im[9]=2.191012402e-01f*r + 9.757021300e-01f*i; }
  { const float r=re[10], i=im[10]; re[10]=9.700312532e-01f*r - 2.429801799e-01f*i; im[10]=2.429801799e-01f*r + 9.700312532e-01f*i; }
  { const float r=re[11], i=im[11]; re[11]=9.637760658e-01f*r - 2.667127575e-01f*i; im[11]=2.667127575e-01f*r + 9.637760658e-01f*i; }
  { const float r=re[12], i=im[12]; re[12]=9.569403357e-01f*r - 2.902846773e-01f*i; im[12]=2.902846773e-01f*r + 9.569403357e-01f*i; }
  { const float r=re[13], i=im[13]; re[13]=9.495281806e-01f*r - 3.136817404e-01f*i; im[13]=3.136817404e-01f*r + 9.495281806e-01f*i; }
  { const float r=re[14], i=im[14]; re[14]=9.415440652e-01f*r - 3.368898534e-01f*i; im[14]=3.368898534e-01f*r + 9.415440652e-01f*i; }
  { const float r=re[15], i=im[15]; re[15]=9.329927988e-01f*r - 3.598950365e-01f*i; im[15]=3.598950365e-01f*r + 9.329927988e-01f*i; }
  { const float r=re[16], i=im[16]; re[16]=9.238795325e-01f*r - 3.826834324e-01f*i; im[16]=3.826834324e-01f*r + 9.238795325e-01f*i; }
  { const float r=re[17], i=im[17]; re[17]=9.142097557e-01f*r - 4.052413140e-01f*i; im[17]=4.052413140e-01f*r + 9.142097557e-01f*i; }
  { const float r=re[18], i=im[18]; re[18]=9.039892931e-01f*r - 4.275550934e-01f*i; im[18]=4.275550934e-01f*r + 9.039892931e-01f*i; }
  { const float r=re[19], i=im[19]; re[19]=8.932243012e-01f*r - 4.496113297e-01f*i; im[19]=4.496113297e-01f*r + 8.932243012e-01f*i; }
  { const float r=re[20], i=im[20]; re[20]=8.819212643e-01f*r - 4.713967368e-01f*i; im[20]=4.713967368e-01f*r + 8.819212643e-01f*i; }
  { const float r=re[21], i=im[21]; re[21]=8.700869911e-01f*r - 4.928981922e-01f*i; im[21]=4.928981922e-01f*r + 8.700869911e-01f*i; }
  { const float r=re[22], i=im[22]; re[22]=8.577286100e-01f*r - 5.141027442e-01f*i; im[22]=5.141027442e-01f*r + 8.577286100e-01f*i; }
  { const float r=re[23], i=im[23]; re[23]=8.448535652e-01f*r - 5.349976199e-01f*i; im[23]=5.349976199e-01f*r + 8.448535652e-01f*i; }
  { const float r=re[24], i=im[24]; re[24]=8.314696123e-01f*r - 5.555702330e-01f*i; im[24]=5.555702330e-01f*r + 8.314696123e-01f*i; }
  { const float r=re[25], i=im[25]; re[25]=8.175848132e-01f*r - 5.758081914e-01f*i; im[25]=5.758081914e-01f*r + 8.175848132e-01f*i; }
  { const float r=re[26], i=im[26]; re[26]=8.032075315e-01f*r - 5.956993045e-01f*i; im[26]=5.956993045e-01f*r + 8.032075315e-01f*i; }
  { const float r=re[27], i=im[27]; re[27]=7.883464276e-01f*r - 6.152315906e-01f*i; im[27]=6.152315906e-01f*r + 7.883464276e-01f*i; }
  { const float r=re[28], i=im[28]; re[28]=7.730104534e-01f*r - 6.343932842e-01f*i; im[28]=6.343932842e-01f*r + 7.730104534e-01f*i; }
  { const float r=re[29], i=im[29]; re[29]=7.572088465e-01f*r - 6.531728430e-01f*i; im[29]=6.531728430e-01f*r + 7.572088465e-01f*i; }
  { const float r=re[30], i=im[30]; re[30]=7.409511254e-01f*r - 6.715589548e-01f*i; im[30]=6.715589548e-01f*r + 7.409511254e-01f*i; }
  { const float r=re[31], i=im[31]; re[31]=7.242470830e-01f*r - 6.895405447e-01f*i; im[31]=6.895405447e-01f*r + 7.242470830e-01f*i; }
  { const float r=re[32], i=im[32]; re[32]=7.071067812e-01f*r - 7.071067812e-01f*i; im[32]=7.071067812e-01f*r + 7.071067812e-01f*i; }
  { const float r=re[33], i=im[33]; re[33]=6.895405447e-01f*r - 7.242470830e-01f*i; im[33]=7.242470830e-01f*r + 6.895405447e-01f*i; }
  { const float r=re[34], i=im[34]; re[34]=6.715589548e-01f*r - 7.409511254e-01f*i; im[34]=7.409511254e-01f*r + 6.715589548e-01f*i; }
  { const float r=re[35], i=im[35]; re[35]=6.531728430e-01f*r - 7.572088465e-01f*i; im[35]=7.572088465e-01f*r + 6.531728430e-01f*i; }
  { const float r=re[36], i=im[36]; re[36]=6.343932842e-01f*r - 7.730104534e-01f*i; im[36]=7.730104534e-01f*r + 6.343932842e-01f*i; }
  { const float r=re[37], i=im[37]; re[37]=6.152315906e-01f*r - 7.883464276e-01f*i; im[37]=7.883464276e-01f*r + 6.152315906e-01f*i; }
  { const float r=re[38], i=im[38]; re[38]=5.956993045e-01f*r - 8.032075315e-01f*i; im[38]=8.032075315e-01f*r + 5.956993045e-01f*i; }
  { const float r=re[39], i=im[39]; re[39]=5.758081914e-01f*r - 8.175848132e-01f*i; im[39]=8.175848132e-01f*r + 5.758081914e-01f*i; }
  { const float r=re[40], i=im[40]; re[40]=5.555702330e-01f*r - 8.314696123e-01f*i; im[40]=8.314696123e-01f*r + 5.555702330e-01f*i; }
  { const float r=re[41], i=im[41]; re[41]=5.349976199e-01f*r - 8.448535652e-01f*i; im[41]=8.448535652e-01f*r + 5.349976199e-01f*i; }
  { const float r=re[42], i=im[42]; re[42]=5.141027442e-01f*r - 8.577286100e-01f*i; im[42]=8.577286100e-01f*r + 5.141027442e-01f*i; }
  { const float r=re[43], i=im[43]; re[43]=4.928981922e-01f*r - 8.700869911e-01f*i; im[43]=8.700869911e-01f*r + 4.928981922e-01f*i; }
  { const float r=re[44], i=im[44]; re[44]=4.713967368e-01f*r - 8.819212643e-01f*i; im[44]=8.819212643e-01f*r + 4.713967368e-01f*i; }
  { const float r=re[45], i=im[45]; re[45]=4.496113297e-01f*r - 8.932243012e-01f*i; im[45]=8.932243012e-01f*r + 4.496113297e-01f*i; }
  { const float r=re[46], i=im[46]; re[46]=4.275550934e-01f*r - 9.039892931e-01f*i; im[46]=9.039892931e-01f*r + 4.275550934e-01f*i; }
  { const float r=re[47], i=im[47]; re[47]=4.052413140e-01f*r - 9.142097557e-01f*i; im[47]=9.142097557e-01f*r + 4.052413140e-01f*i; }
  { const float r=re[48], i=im[48]; re[48]=3.826834324e-01f*r - 9.238795325e-01f*i; im[48]=9.238795325e-01f*r + 3.826834324e-01f*i; }
  { const float r=re[49], i=im[49]; re[49]=3.598950365e-01f*r - 9.329927988e-01f*i; im[49]=9.329927988e-01f*r + 3.598950365e-01f*i; }
  { const float r=re[50], i=im[50]; re[50]=3.368898534e-01f*r - 9.415440652e-01f*i; im[50]=9.415440652e-01f*r + 3.368898534e-01f*i; }
  { const float r=re[51], i=im[51]; re[51]=3.136817404e-01f*r - 9.495281806e-01f*i; im[51]=9.495281806e-01f*r + 3.136817404e-01f*i; }
  { const float r=re[52], i=im[52]; re[52]=2.902846773e-01f*r - 9.569403357e-01f*i; im[52]=9.569403357e-01f*r + 2.902846773e-01f*i; }
  { const float r=re[53], i=im[53]; re[53]=2.667127575e-01f*r - 9.637760658e-01f*i; im[53]=9.637760658e-01f*r + 2.667127575e-01f*i; }
  { const float r=re[54], i=im[54]; re[54]=2.429801799e-01f*r - 9.700312532e-01f*i; im[54]=9.700312532e-01f*r + 2.429801799e-01f*i; }
  { const float r=re[55], i=im[55]; re[55]=2.191012402e-01f*r - 9.757021300e-01f*i; im[55]=9.757021300e-01f*r + 2.191012402e-01f*i; }
  { const float r=re[56], i=im[56]; re[56]=1.950903220e-01f*r - 9.807852804e-01f*i; im[56]=9.807852804e-01f*r + 1.950903220e-01f*i; }
  { const float r=re[57], i=im[57]; re[57]=1.709618888e-01f*r - 9.852776424e-01f*i; im[57]=9.852776424e-01f*r + 1.709618888e-01f*i; }
  { const float r=re[58], i=im[58]; re[58]=1.467304745e-01f*r - 9.891765100e-01f*i; im[58]=9.891765100e-01f*r + 1.467304745e-01f*i; }
  { const float r=re[59], i=im[59]; re[59]=1.224106752e-01f*r - 9.924795346e-01f*i; im[59]=9.924795346e-01f*r + 1.224106752e-01f*i; }
  { const float r=re[60], i=im[60]; re[60]=9.801714033e-02f*r - 9.951847267e-01f*i; im[60]=9.951847267e-01f*r + 9.801714033e-02f*i; }
  { const float r=re[61], i=im[61]; re[61]=7.356456360e-02f*r - 9.972904567e-01f*i; im[61]=9.972904567e-01f*r + 7.356456360e-02f*i; }
  { const float r=re[62], i=im[62]; re[62]=4.906767433e-02f*r - 9.987954562e-01f*i; im[62]=9.987954562e-01f*r + 4.906767433e-02f*i; }
  { const float r=re[63], i=im[63]; re[63]=2.454122852e-02f*r - 9.996988187e-01f*i; im[63]=9.996988187e-01f*r + 2.454122852e-02f*i; }
}
__device__ __forceinline__ void hermitian_pack_inplace(float* __restrict__ re, float* __restrict__ im) {
  { const float r=re[0]; re[0]=r; im[0]=r; }
  { const float r=re[32], i=im[32]; re[32]=r; im[32]=-i; }
  {
    const float ar=re[1], ai=im[1], br=re[63], bi=im[63];
    const float h1r=0.5f*(ar+br), h1i=0.5f*(ai-bi);
    const float a2r=9.987954562e-01f*ar - 4.906767433e-02f*ai, a2i=4.906767433e-02f*ar + 9.987954562e-01f*ai;
    const float b2r=-9.987954562e-01f*br - 4.906767433e-02f*bi, b2i=4.906767433e-02f*br + -9.987954562e-01f*bi;
    const float h2r=0.5f*(a2r+b2r), h2i=0.5f*(a2i-b2i);
    re[1]=h1r-h2i; im[1]=h1i+h2r;
    re[63]=h1r+h2i; im[63]=-h1i+h2r;
  }
  {
    const float ar=re[2], ai=im[2], br=re[62], bi=im[62];
    const float h1r=0.5f*(ar+br), h1i=0.5f*(ai-bi);
    const float a2r=9.951847267e-01f*ar - 9.801714033e-02f*ai, a2i=9.801714033e-02f*ar + 9.951847267e-01f*ai;
    const float b2r=-9.951847267e-01f*br - 9.801714033e-02f*bi, b2i=9.801714033e-02f*br + -9.951847267e-01f*bi;
    const float h2r=0.5f*(a2r+b2r), h2i=0.5f*(a2i-b2i);
    re[2]=h1r-h2i; im[2]=h1i+h2r;
    re[62]=h1r+h2i; im[62]=-h1i+h2r;
  }
  {
    const float ar=re[3], ai=im[3], br=re[61], bi=im[61];
    const float h1r=0.5f*(ar+br), h1i=0.5f*(ai-bi);
    const float a2r=9.891765100e-01f*ar - 1.467304745e-01f*ai, a2i=1.467304745e-01f*ar + 9.891765100e-01f*ai;
    const float b2r=-9.891765100e-01f*br - 1.467304745e-01f*bi, b2i=1.467304745e-01f*br + -9.891765100e-01f*bi;
    const float h2r=0.5f*(a2r+b2r), h2i=0.5f*(a2i-b2i);
    re[3]=h1r-h2i; im[3]=h1i+h2r;
    re[61]=h1r+h2i; im[61]=-h1i+h2r;
  }
  {
    const float ar=re[4], ai=im[4], br=re[60], bi=im[60];
    const float h1r=0.5f*(ar+br), h1i=0.5f*(ai-bi);
    const float a2r=9.807852804e-01f*ar - 1.950903220e-01f*ai, a2i=1.950903220e-01f*ar + 9.807852804e-01f*ai;
    const float b2r=-9.807852804e-01f*br - 1.950903220e-01f*bi, b2i=1.950903220e-01f*br + -9.807852804e-01f*bi;
    const float h2r=0.5f*(a2r+b2r), h2i=0.5f*(a2i-b2i);
    re[4]=h1r-h2i; im[4]=h1i+h2r;
    re[60]=h1r+h2i; im[60]=-h1i+h2r;
  }
  {
    const float ar=re[5], ai=im[5], br=re[59], bi=im[59];
    const float h1r=0.5f*(ar+br), h1i=0.5f*(ai-bi);
    const float a2r=9.700312532e-01f*ar - 2.429801799e-01f*ai, a2i=2.429801799e-01f*ar + 9.700312532e-01f*ai;
    const float b2r=-9.700312532e-01f*br - 2.429801799e-01f*bi, b2i=2.429801799e-01f*br + -9.700312532e-01f*bi;
    const float h2r=0.5f*(a2r+b2r), h2i=0.5f*(a2i-b2i);
    re[5]=h1r-h2i; im[5]=h1i+h2r;
    re[59]=h1r+h2i; im[59]=-h1i+h2r;
  }
  {
    const float ar=re[6], ai=im[6], br=re[58], bi=im[58];
    const float h1r=0.5f*(ar+br), h1i=0.5f*(ai-bi);
    const float a2r=9.569403357e-01f*ar - 2.902846773e-01f*ai, a2i=2.902846773e-01f*ar + 9.569403357e-01f*ai;
    const float b2r=-9.569403357e-01f*br - 2.902846773e-01f*bi, b2i=2.902846773e-01f*br + -9.569403357e-01f*bi;
    const float h2r=0.5f*(a2r+b2r), h2i=0.5f*(a2i-b2i);
    re[6]=h1r-h2i; im[6]=h1i+h2r;
    re[58]=h1r+h2i; im[58]=-h1i+h2r;
  }
  {
    const float ar=re[7], ai=im[7], br=re[57], bi=im[57];
    const float h1r=0.5f*(ar+br), h1i=0.5f*(ai-bi);
    const float a2r=9.415440652e-01f*ar - 3.368898534e-01f*ai, a2i=3.368898534e-01f*ar + 9.415440652e-01f*ai;
    const float b2r=-9.415440652e-01f*br - 3.368898534e-01f*bi, b2i=3.368898534e-01f*br + -9.415440652e-01f*bi;
    const float h2r=0.5f*(a2r+b2r), h2i=0.5f*(a2i-b2i);
    re[7]=h1r-h2i; im[7]=h1i+h2r;
    re[57]=h1r+h2i; im[57]=-h1i+h2r;
  }
  {
    const float ar=re[8], ai=im[8], br=re[56], bi=im[56];
    const float h1r=0.5f*(ar+br), h1i=0.5f*(ai-bi);
    const float a2r=9.238795325e-01f*ar - 3.826834324e-01f*ai, a2i=3.826834324e-01f*ar + 9.238795325e-01f*ai;
    const float b2r=-9.238795325e-01f*br - 3.826834324e-01f*bi, b2i=3.826834324e-01f*br + -9.238795325e-01f*bi;
    const float h2r=0.5f*(a2r+b2r), h2i=0.5f*(a2i-b2i);
    re[8]=h1r-h2i; im[8]=h1i+h2r;
    re[56]=h1r+h2i; im[56]=-h1i+h2r;
  }
  {
    const float ar=re[9], ai=im[9], br=re[55], bi=im[55];
    const float h1r=0.5f*(ar+br), h1i=0.5f*(ai-bi);
    const float a2r=9.039892931e-01f*ar - 4.275550934e-01f*ai, a2i=4.275550934e-01f*ar + 9.039892931e-01f*ai;
    const float b2r=-9.039892931e-01f*br - 4.275550934e-01f*bi, b2i=4.275550934e-01f*br + -9.039892931e-01f*bi;
    const float h2r=0.5f*(a2r+b2r), h2i=0.5f*(a2i-b2i);
    re[9]=h1r-h2i; im[9]=h1i+h2r;
    re[55]=h1r+h2i; im[55]=-h1i+h2r;
  }
  {
    const float ar=re[10], ai=im[10], br=re[54], bi=im[54];
    const float h1r=0.5f*(ar+br), h1i=0.5f*(ai-bi);
    const float a2r=8.819212643e-01f*ar - 4.713967368e-01f*ai, a2i=4.713967368e-01f*ar + 8.819212643e-01f*ai;
    const float b2r=-8.819212643e-01f*br - 4.713967368e-01f*bi, b2i=4.713967368e-01f*br + -8.819212643e-01f*bi;
    const float h2r=0.5f*(a2r+b2r), h2i=0.5f*(a2i-b2i);
    re[10]=h1r-h2i; im[10]=h1i+h2r;
    re[54]=h1r+h2i; im[54]=-h1i+h2r;
  }
  {
    const float ar=re[11], ai=im[11], br=re[53], bi=im[53];
    const float h1r=0.5f*(ar+br), h1i=0.5f*(ai-bi);
    const float a2r=8.577286100e-01f*ar - 5.141027442e-01f*ai, a2i=5.141027442e-01f*ar + 8.577286100e-01f*ai;
    const float b2r=-8.577286100e-01f*br - 5.141027442e-01f*bi, b2i=5.141027442e-01f*br + -8.577286100e-01f*bi;
    const float h2r=0.5f*(a2r+b2r), h2i=0.5f*(a2i-b2i);
    re[11]=h1r-h2i; im[11]=h1i+h2r;
    re[53]=h1r+h2i; im[53]=-h1i+h2r;
  }
  {
    const float ar=re[12], ai=im[12], br=re[52], bi=im[52];
    const float h1r=0.5f*(ar+br), h1i=0.5f*(ai-bi);
    const float a2r=8.314696123e-01f*ar - 5.555702330e-01f*ai, a2i=5.555702330e-01f*ar + 8.314696123e-01f*ai;
    const float b2r=-8.314696123e-01f*br - 5.555702330e-01f*bi, b2i=5.555702330e-01f*br + -8.314696123e-01f*bi;
    const float h2r=0.5f*(a2r+b2r), h2i=0.5f*(a2i-b2i);
    re[12]=h1r-h2i; im[12]=h1i+h2r;
    re[52]=h1r+h2i; im[52]=-h1i+h2r;
  }
  {
    const float ar=re[13], ai=im[13], br=re[51], bi=im[51];
    const float h1r=0.5f*(ar+br), h1i=0.5f*(ai-bi);
    const float a2r=8.032075315e-01f*ar - 5.956993045e-01f*ai, a2i=5.956993045e-01f*ar + 8.032075315e-01f*ai;
    const float b2r=-8.032075315e-01f*br - 5.956993045e-01f*bi, b2i=5.956993045e-01f*br + -8.032075315e-01f*bi;
    const float h2r=0.5f*(a2r+b2r), h2i=0.5f*(a2i-b2i);
    re[13]=h1r-h2i; im[13]=h1i+h2r;
    re[51]=h1r+h2i; im[51]=-h1i+h2r;
  }
  {
    const float ar=re[14], ai=im[14], br=re[50], bi=im[50];
    const float h1r=0.5f*(ar+br), h1i=0.5f*(ai-bi);
    const float a2r=7.730104534e-01f*ar - 6.343932842e-01f*ai, a2i=6.343932842e-01f*ar + 7.730104534e-01f*ai;
    const float b2r=-7.730104534e-01f*br - 6.343932842e-01f*bi, b2i=6.343932842e-01f*br + -7.730104534e-01f*bi;
    const float h2r=0.5f*(a2r+b2r), h2i=0.5f*(a2i-b2i);
    re[14]=h1r-h2i; im[14]=h1i+h2r;
    re[50]=h1r+h2i; im[50]=-h1i+h2r;
  }
  {
    const float ar=re[15], ai=im[15], br=re[49], bi=im[49];
    const float h1r=0.5f*(ar+br), h1i=0.5f*(ai-bi);
    const float a2r=7.409511254e-01f*ar - 6.715589548e-01f*ai, a2i=6.715589548e-01f*ar + 7.409511254e-01f*ai;
    const float b2r=-7.409511254e-01f*br - 6.715589548e-01f*bi, b2i=6.715589548e-01f*br + -7.409511254e-01f*bi;
    const float h2r=0.5f*(a2r+b2r), h2i=0.5f*(a2i-b2i);
    re[15]=h1r-h2i; im[15]=h1i+h2r;
    re[49]=h1r+h2i; im[49]=-h1i+h2r;
  }
  {
    const float ar=re[16], ai=im[16], br=re[48], bi=im[48];
    const float h1r=0.5f*(ar+br), h1i=0.5f*(ai-bi);
    const float a2r=7.071067812e-01f*ar - 7.071067812e-01f*ai, a2i=7.071067812e-01f*ar + 7.071067812e-01f*ai;
    const float b2r=-7.071067812e-01f*br - 7.071067812e-01f*bi, b2i=7.071067812e-01f*br + -7.071067812e-01f*bi;
    const float h2r=0.5f*(a2r+b2r), h2i=0.5f*(a2i-b2i);
    re[16]=h1r-h2i; im[16]=h1i+h2r;
    re[48]=h1r+h2i; im[48]=-h1i+h2r;
  }
  {
    const float ar=re[17], ai=im[17], br=re[47], bi=im[47];
    const float h1r=0.5f*(ar+br), h1i=0.5f*(ai-bi);
    const float a2r=6.715589548e-01f*ar - 7.409511254e-01f*ai, a2i=7.409511254e-01f*ar + 6.715589548e-01f*ai;
    const float b2r=-6.715589548e-01f*br - 7.409511254e-01f*bi, b2i=7.409511254e-01f*br + -6.715589548e-01f*bi;
    const float h2r=0.5f*(a2r+b2r), h2i=0.5f*(a2i-b2i);
    re[17]=h1r-h2i; im[17]=h1i+h2r;
    re[47]=h1r+h2i; im[47]=-h1i+h2r;
  }
  {
    const float ar=re[18], ai=im[18], br=re[46], bi=im[46];
    const float h1r=0.5f*(ar+br), h1i=0.5f*(ai-bi);
    const float a2r=6.343932842e-01f*ar - 7.730104534e-01f*ai, a2i=7.730104534e-01f*ar + 6.343932842e-01f*ai;
    const float b2r=-6.343932842e-01f*br - 7.730104534e-01f*bi, b2i=7.730104534e-01f*br + -6.343932842e-01f*bi;
    const float h2r=0.5f*(a2r+b2r), h2i=0.5f*(a2i-b2i);
    re[18]=h1r-h2i; im[18]=h1i+h2r;
    re[46]=h1r+h2i; im[46]=-h1i+h2r;
  }
  {
    const float ar=re[19], ai=im[19], br=re[45], bi=im[45];
    const float h1r=0.5f*(ar+br), h1i=0.5f*(ai-bi);
    const float a2r=5.956993045e-01f*ar - 8.032075315e-01f*ai, a2i=8.032075315e-01f*ar + 5.956993045e-01f*ai;
    const float b2r=-5.956993045e-01f*br - 8.032075315e-01f*bi, b2i=8.032075315e-01f*br + -5.956993045e-01f*bi;
    const float h2r=0.5f*(a2r+b2r), h2i=0.5f*(a2i-b2i);
    re[19]=h1r-h2i; im[19]=h1i+h2r;
    re[45]=h1r+h2i; im[45]=-h1i+h2r;
  }
  {
    const float ar=re[20], ai=im[20], br=re[44], bi=im[44];
    const float h1r=0.5f*(ar+br), h1i=0.5f*(ai-bi);
    const float a2r=5.555702330e-01f*ar - 8.314696123e-01f*ai, a2i=8.314696123e-01f*ar + 5.555702330e-01f*ai;
    const float b2r=-5.555702330e-01f*br - 8.314696123e-01f*bi, b2i=8.314696123e-01f*br + -5.555702330e-01f*bi;
    const float h2r=0.5f*(a2r+b2r), h2i=0.5f*(a2i-b2i);
    re[20]=h1r-h2i; im[20]=h1i+h2r;
    re[44]=h1r+h2i; im[44]=-h1i+h2r;
  }
  {
    const float ar=re[21], ai=im[21], br=re[43], bi=im[43];
    const float h1r=0.5f*(ar+br), h1i=0.5f*(ai-bi);
    const float a2r=5.141027442e-01f*ar - 8.577286100e-01f*ai, a2i=8.577286100e-01f*ar + 5.141027442e-01f*ai;
    const float b2r=-5.141027442e-01f*br - 8.577286100e-01f*bi, b2i=8.577286100e-01f*br + -5.141027442e-01f*bi;
    const float h2r=0.5f*(a2r+b2r), h2i=0.5f*(a2i-b2i);
    re[21]=h1r-h2i; im[21]=h1i+h2r;
    re[43]=h1r+h2i; im[43]=-h1i+h2r;
  }
  {
    const float ar=re[22], ai=im[22], br=re[42], bi=im[42];
    const float h1r=0.5f*(ar+br), h1i=0.5f*(ai-bi);
    const float a2r=4.713967368e-01f*ar - 8.819212643e-01f*ai, a2i=8.819212643e-01f*ar + 4.713967368e-01f*ai;
    const float b2r=-4.713967368e-01f*br - 8.819212643e-01f*bi, b2i=8.819212643e-01f*br + -4.713967368e-01f*bi;
    const float h2r=0.5f*(a2r+b2r), h2i=0.5f*(a2i-b2i);
    re[22]=h1r-h2i; im[22]=h1i+h2r;
    re[42]=h1r+h2i; im[42]=-h1i+h2r;
  }
  {
    const float ar=re[23], ai=im[23], br=re[41], bi=im[41];
    const float h1r=0.5f*(ar+br), h1i=0.5f*(ai-bi);
    const float a2r=4.275550934e-01f*ar - 9.039892931e-01f*ai, a2i=9.039892931e-01f*ar + 4.275550934e-01f*ai;
    const float b2r=-4.275550934e-01f*br - 9.039892931e-01f*bi, b2i=9.039892931e-01f*br + -4.275550934e-01f*bi;
    const float h2r=0.5f*(a2r+b2r), h2i=0.5f*(a2i-b2i);
    re[23]=h1r-h2i; im[23]=h1i+h2r;
    re[41]=h1r+h2i; im[41]=-h1i+h2r;
  }
  {
    const float ar=re[24], ai=im[24], br=re[40], bi=im[40];
    const float h1r=0.5f*(ar+br), h1i=0.5f*(ai-bi);
    const float a2r=3.826834324e-01f*ar - 9.238795325e-01f*ai, a2i=9.238795325e-01f*ar + 3.826834324e-01f*ai;
    const float b2r=-3.826834324e-01f*br - 9.238795325e-01f*bi, b2i=9.238795325e-01f*br + -3.826834324e-01f*bi;
    const float h2r=0.5f*(a2r+b2r), h2i=0.5f*(a2i-b2i);
    re[24]=h1r-h2i; im[24]=h1i+h2r;
    re[40]=h1r+h2i; im[40]=-h1i+h2r;
  }
  {
    const float ar=re[25], ai=im[25], br=re[39], bi=im[39];
    const float h1r=0.5f*(ar+br), h1i=0.5f*(ai-bi);
    const float a2r=3.368898534e-01f*ar - 9.415440652e-01f*ai, a2i=9.415440652e-01f*ar + 3.368898534e-01f*ai;
    const float b2r=-3.368898534e-01f*br - 9.415440652e-01f*bi, b2i=9.415440652e-01f*br + -3.368898534e-01f*bi;
    const float h2r=0.5f*(a2r+b2r), h2i=0.5f*(a2i-b2i);
    re[25]=h1r-h2i; im[25]=h1i+h2r;
    re[39]=h1r+h2i; im[39]=-h1i+h2r;
  }
  {
    const float ar=re[26], ai=im[26], br=re[38], bi=im[38];
    const float h1r=0.5f*(ar+br), h1i=0.5f*(ai-bi);
    const float a2r=2.902846773e-01f*ar - 9.569403357e-01f*ai, a2i=9.569403357e-01f*ar + 2.902846773e-01f*ai;
    const float b2r=-2.902846773e-01f*br - 9.569403357e-01f*bi, b2i=9.569403357e-01f*br + -2.902846773e-01f*bi;
    const float h2r=0.5f*(a2r+b2r), h2i=0.5f*(a2i-b2i);
    re[26]=h1r-h2i; im[26]=h1i+h2r;
    re[38]=h1r+h2i; im[38]=-h1i+h2r;
  }
  {
    const float ar=re[27], ai=im[27], br=re[37], bi=im[37];
    const float h1r=0.5f*(ar+br), h1i=0.5f*(ai-bi);
    const float a2r=2.429801799e-01f*ar - 9.700312532e-01f*ai, a2i=9.700312532e-01f*ar + 2.429801799e-01f*ai;
    const float b2r=-2.429801799e-01f*br - 9.700312532e-01f*bi, b2i=9.700312532e-01f*br + -2.429801799e-01f*bi;
    const float h2r=0.5f*(a2r+b2r), h2i=0.5f*(a2i-b2i);
    re[27]=h1r-h2i; im[27]=h1i+h2r;
    re[37]=h1r+h2i; im[37]=-h1i+h2r;
  }
  {
    const float ar=re[28], ai=im[28], br=re[36], bi=im[36];
    const float h1r=0.5f*(ar+br), h1i=0.5f*(ai-bi);
    const float a2r=1.950903220e-01f*ar - 9.807852804e-01f*ai, a2i=9.807852804e-01f*ar + 1.950903220e-01f*ai;
    const float b2r=-1.950903220e-01f*br - 9.807852804e-01f*bi, b2i=9.807852804e-01f*br + -1.950903220e-01f*bi;
    const float h2r=0.5f*(a2r+b2r), h2i=0.5f*(a2i-b2i);
    re[28]=h1r-h2i; im[28]=h1i+h2r;
    re[36]=h1r+h2i; im[36]=-h1i+h2r;
  }
  {
    const float ar=re[29], ai=im[29], br=re[35], bi=im[35];
    const float h1r=0.5f*(ar+br), h1i=0.5f*(ai-bi);
    const float a2r=1.467304745e-01f*ar - 9.891765100e-01f*ai, a2i=9.891765100e-01f*ar + 1.467304745e-01f*ai;
    const float b2r=-1.467304745e-01f*br - 9.891765100e-01f*bi, b2i=9.891765100e-01f*br + -1.467304745e-01f*bi;
    const float h2r=0.5f*(a2r+b2r), h2i=0.5f*(a2i-b2i);
    re[29]=h1r-h2i; im[29]=h1i+h2r;
    re[35]=h1r+h2i; im[35]=-h1i+h2r;
  }
  {
    const float ar=re[30], ai=im[30], br=re[34], bi=im[34];
    const float h1r=0.5f*(ar+br), h1i=0.5f*(ai-bi);
    const float a2r=9.801714033e-02f*ar - 9.951847267e-01f*ai, a2i=9.951847267e-01f*ar + 9.801714033e-02f*ai;
    const float b2r=-9.801714033e-02f*br - 9.951847267e-01f*bi, b2i=9.951847267e-01f*br + -9.801714033e-02f*bi;
    const float h2r=0.5f*(a2r+b2r), h2i=0.5f*(a2i-b2i);
    re[30]=h1r-h2i; im[30]=h1i+h2r;
    re[34]=h1r+h2i; im[34]=-h1i+h2r;
  }
  {
    const float ar=re[31], ai=im[31], br=re[33], bi=im[33];
    const float h1r=0.5f*(ar+br), h1i=0.5f*(ai-bi);
    const float a2r=4.906767433e-02f*ar - 9.987954562e-01f*ai, a2i=9.987954562e-01f*ar + 4.906767433e-02f*ai;
    const float b2r=-4.906767433e-02f*br - 9.987954562e-01f*bi, b2i=9.987954562e-01f*br + -4.906767433e-02f*bi;
    const float h2r=0.5f*(a2r+b2r), h2i=0.5f*(a2i-b2i);
    re[31]=h1r-h2i; im[31]=h1i+h2r;
    re[33]=h1r+h2i; im[33]=-h1i+h2r;
  }
}
